name: taily-app
type: laravel
docroot: public
php_version: "8.3"
webserver_type: apache-fpm
xdebug_enabled: false
database:
    type: mysql
    version: "8.4"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
